### ISSUE TITLE
Missing details in Manta Pacific Replica Node instructions

### ISSUE THREAD

**Issue by jakobilobi** [Manta-Network/docs#266]
Greetings Manta devs,

The past week I've been working on getting a Manta Pacific node up and running, with the intention of using it as an RPC node. While the setup following the instructions at first worked well, the node has not been able to sync all the way to the latest block. In some curious way, it's stuck ~26,150 blocks behind the current head, syncing at the same speed as the chain but never catching up.

I've read and used the instructions in the docs ([Replica Node page](https://docs.manta.network/docs/manta-pacific/Replica%20Node)) as well as in [this Notion article](https://constellationlabs.notion.site/Manta-Pacific-Replica-Node-64219c65097940489d8277f454153193). The `op-node` image in use is `celestia-3.0.0-dencun`, as advised, but no matter how hard I've been searching haven't found instructions on how to set up and connect a Celestia Light node. Of course, there's [the official Celestia documentation](https://docs.celestia.org/nodes/light-node) on how to do that, but that still leaves the issue of missing instructions on how to properly connect the nodes. There's this line in the documentation, but then there's no mention about it in the actual zipfile:

> The updated replica scripts will help users provision this Celestia light node and connect to it in the same way Manta Pacific will.

My request is simply: can you update the Replica Node instructions (text and/or zipfile) with enough details to help devs like me to get a node up and running properly?

PS. I already asked about assistance [in the Discord](https://discord.com/channels/795390654628102165/1121274625687552080/1230150679662694472) but I figure there might be some value in opening a ticket here as well.

Cheers,
Jakob

**Comment by jakobilobi** [comment]
Update:

I actually did find the Celestia Light node included in the `docker-compose.yml` file of the zipfile in [the Notion article](https://constellationlabs.notion.site/Manta-Pacific-Replica-Node-64219c65097940489d8277f454153193). Would be great if this was the zipfile that the links in your Docs page let you download as well. Updating that would relieve a lot of confusion!

**Comment by jincan39** [comment]
Thanks for the details, the latest doc has been updated.
https://docs.manta.network/docs/manta-pacific/Manta%20Pacific%20Node/How%20to%20run%20Replica%20Node
